In [7]:
!pip install requests pandas plotly -q

import requests
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import time

In [8]:
url = "https://api.coingecko.com/api/v3/coins/markets"
params = {
    "vs_currency": "usd",
    "order": "market_cap_desc",
    "per_page": 10,
    "page": 1,
    "sparkline": "true",
    "price_change_percentage": "24h,7d"
}

response = requests.get(url, params=params)
print("Status code:", response.status_code)
data = response.json()
print(type(data), len(data) if isinstance(data, list) else data)
df = pd.json_normalize(data)
print(df.columns.tolist())
df.head()

Status code: 200
<class 'list'> 10
['id', 'symbol', 'name', 'image', 'current_price', 'market_cap', 'market_cap_rank', 'fully_diluted_valuation', 'total_volume', 'high_24h', 'low_24h', 'price_change_24h', 'price_change_percentage_24h', 'market_cap_change_24h', 'market_cap_change_percentage_24h', 'circulating_supply', 'total_supply', 'max_supply', 'ath', 'ath_change_percentage', 'ath_date', 'atl', 'atl_change_percentage', 'atl_date', 'roi', 'last_updated', 'price_change_percentage_24h_in_currency', 'price_change_percentage_7d_in_currency', 'sparkline_in_7d.price', 'roi.times', 'roi.currency', 'roi.percentage']

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,atl_change_percentage,atl_date,roi,last_updated,price_change_percentage_24h_in_currency,price_change_percentage_7d_in_currency,sparkline_in_7d.price,roi.times,roi.currency,roi.percentage
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,61658.000000,1236583096242,1,1236583096242,42980279200,62060.000000,...,9.082829e+04,2013-07-06T00:00:00.000Z,NaN,2026-07-02T18:58:01.964Z,2.598943,3.566800,"[59430.91825964714, 59237.365253537, 59312.805...",NaN,NaN,NaN
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1699.440000,205138029728,2,205138029728,14512268714,1717.430000,...,3.923999e+05,2015-10-20T00:00:00.000Z,NaN,2026-07-02T18:57:55.928Z,5.270740,8.960731,"[1565.6252713481706, 1557.4253434203486, 1556....",35.851236,btc,3585.123551
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999044,184103829379,3,189565253613,64841059739,0.999087,...,7.450103e+01,2015-03-02T00:00:00.000Z,NaN,2026-07-02T18:57:53.611Z,0.014030,0.040815,"[0.9985813841992665, 0.998524377093521, 0.9984...",NaN,NaN,NaN
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,559.540000,75426384078,4,75426383216,842221761,565.900000,...,1.405190e+06,2017-10-19T00:00:00.000Z,NaN,2026-07-02T18:58:02.202Z,1.320598,1.143393,"[558.4510401831724, 554.95719173652, 553.44816...",NaN,NaN,NaN
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,0.999852,73366030335,5,73424618859,13729011280,0.999907,...,1.391709e+01,2023-03-11T08:02:13.981Z,NaN,2026-07-02T18:57:58.214Z,0.021804,0.010641,"[0.9999229786737812, 0.999685524154682, 0.9996...",NaN,NaN,NaN

In [9]:
df = pd.json_normalize(data)

df = df[[
    "id", "symbol", "current_price", "market_cap",
    "total_volume", "price_change_percentage_24h",
    "price_change_percentage_7d_in_currency",
    "sparkline_in_7d.price"
]]

df.columns = ["coin", "symbol", "price_usd", "market_cap",
              "volume_24h", "change_24h", "change_7d", "sparkline"]

df

,coin,symbol,price_usd,market_cap,volume_24h,change_24h,change_7d,sparkline
0,bitcoin,btc,61658.000000,1236583096242,42980279200,2.59894,3.566800,"[59430.91825964714, 59237.365253537, 59312.805..."
1,ethereum,eth,1699.440000,205138029728,14512268714,5.27074,8.960731,"[1565.6252713481706, 1557.4253434203486, 1556...."
2,tether,usdt,0.999044,184103829379,64841059739,0.01403,0.040815,"[0.9985813841992665, 0.998524377093521, 0.9984..."
3,binancecoin,bnb,559.540000,75426384078,842221761,1.32060,1.143393,"[558.4510401831724, 554.95719173652, 553.44816..."
4,usd-coin,usdc,0.999852,73366030335,13729011280,0.02180,0.010641,"[0.9999229786737812, 0.999685524154682, 0.9996..."
5,ripple,xrp,1.087000,67713325888,1867208533,2.72328,5.717581,"[1.0337591960416277, 1.0311408683749874, 1.030..."
6,solana,sol,80.970000,47054936713,4152822707,4.71456,21.293191,"[66.07130400926837, 65.90177372287786, 66.0799..."
7,tron,trx,0.317652,30129088203,421054432,0.05994,-1.634534,"[0.32397121308732607, 0.3234617030686344, 0.32..."
8,figure-heloc,figr_heloc,1.034000,20173587676,19675570,2.03069,0.576271,"[1.0293055, 1.0293805, 1.0358594, 1.0358243, 1..."
9,hyperliquid,hype,66.820000,14862019547,582713668,4.74375,8.904189,"[63.328833931592946, 62.89553981764749, 63.118..."

In [11]:
fig = go.Figure()
for i, row in df.iterrows():
    fig.add_trace(go.Scatter(
        y=row["sparkline"],
        mode="lines", name=row["coin"]
    ))
fig.update_layout(title="7-Day Price Trend — Top 10 Coins", template="plotly_dark",
                   xaxis_title="Hours (last 7 days)", yaxis_title="Price (USD)")
fig.show()

In [14]:

sparkline_dict = {row["coin"]: row["sparkline"] for _, row in df.iterrows()}


lengths = {k: len(v) for k, v in sparkline_dict.items()}
print(lengths)


min_len = min(lengths.values())
sparkline_dict = {k: v[:min_len] for k, v in sparkline_dict.items()}

price_matrix = pd.DataFrame(sparkline_dict)
corr = price_matrix.corr()

fig = px.imshow(corr, text_auto=".2f", color_continuous_scale="RdBu_r",
                 title="7-Day Price Correlation Between Top 10 Coins")
fig.show()

{'bitcoin': 168, 'ethereum': 168, 'tether': 167, 'binancecoin': 169, 'usd-coin': 169, 'ripple': 168, 'solana': 168, 'tron': 168, 'figure-heloc': 128, 'hyperliquid': 168}